### ISSUE TITLE
Why the nonfree license?

### ISSUE THREAD

**Issue by JonathanHelianthicusDoe** [rust-rum/hal-drv-dht#1]
I mean, I get that it&rsquo;s a joke, but [using a nonfree license for the sake of a joke has already been done before, and it wasn&rsquo;t a great idea the first time](https://en.wikipedia.org/wiki/Douglas_Crockford#%22Good,_not_Evil%22).

**Comment by rumatoest** [comment]
I'm really pleased that you've asked about this in less than 4 hour after I've published first release.

Actually I'm not seeing  any restrictions in GitHub terms for using customized licenses.

Also I presume that more that 95% of all dozen developers who would ever use my driver would comply with my terms and conditions.

BTW I think this license is more appropriate than [WTFPL](https://en.wikipedia.org/wiki/WTFPL) that I planned to use initially.

**Comment by JonathanHelianthicusDoe** [comment]
> Actually I'm not seeing any restrictions in GitHub terms for using customized licenses.

There is plenty of nonfree source code on GitHub, and this has been the case for A Very Long Time&trade;.

> Also I presume that more that 95% of all dozen developers who would ever use my driver would comply with my terms and conditions.

I don&rsquo;t doubt you here, but I think it&rsquo;s worth just using a free license rather than keeping your code proprietary for no real reason!

> BTW I think this license is more appropriate than WTFPL that I planned to use initially.

Well, the WTFPL might be [a crayon license](https://opensource.stackexchange.com/questions/1445/how-can-a-crayon-license-be-a-problem), but at least it is a free software license. If what you want is a public domain dedication (essentially the WTFPL), then the usual suspect is the [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by rumatoest** [comment]
> I think it’s worth just using a free license rather than keeping your code proprietary for no real reason!

Well my answer have to be simple. 

1. I wrote this code
2. I've suffered a lot until I was able to find proper solution
3. That is why I deserve to  publish it under any license I want

**Comment by JonathanHelianthicusDoe** [comment]
> 1. I wrote this code
> 2. I've suffered a lot until I was able to find proper solution
> 3. That is why I deserve to publish it under any license I want

In order to actually answer me, you would have to go further than this, certainly! I imagine this is what you have in mind to continue this train of thought, but did not write:

> 4&#46; I want to publish this code under a nonfree license (the pickle license).
> 5&#46; Because I deserve to publish it under any license I want, and what I want is the nonfree license, that is sufficient reason to pick the pickle license.

1&#46; and 2&#46; are completely irrelevant here, of course&hellip; if you wrote the code then you are legally entitled to license it however you want, or even to not license it at all and keep it to yourself. So 3&#46; is true, but not because of 1&#46; and 2&#46;!

What I&rsquo;m saying is that **there is no reason for 4&#46;** The pickle license is a joke and all it does is make your software not part of the enormous body of free-as-in-freedom software that exists in the world today and in the future. It does not secure you any rights, since the Expat license on which you based the pickle license already gives everything away; if anyone&rsquo;s rights are preserved here, it is those of the pickles&hellip;

**Comment by rumatoest** [comment]
Well I've just realized that I have this conversation with a deer from Toontown (according to profile) who registered at github less than 1 year ago.

And because you are so insisting this leads me to conclusion that you are the one whose actions could possibly violate my current terms and conditions. That is why you are trying convince me to change license. In this case you could do the things you want to do without any license restrictions.
